export const certificatesData = [
  {
    id: "mcp",
    title: "Introduction to Model Context Protocol",
    issuer: "Anthropic",
    date: "March 2026",
    image: "/certificates/WhatsApp Image 2026-03-16 at 5.48.06 PM (2).jpeg",
  },
  {
    id: "chatgpt",
    title: "ChatGPT Bootcamp",
    issuer: "LetsUpgrade",
    date: "Feb 2025",
    image: "/certificates/WhatsApp Image 2026-03-16 at 5.48.05 PM.jpeg",
  },
  {
    id: "canva-feb",
    title: "Canva Bootcamp",
    issuer: "LetsUpgrade",
    date: "Feb 2025",
    image: "/certificates/iool.png",
  },
  {
    id: "smm",
    title: "Social Media Marketing Bootcamp",
    issuer: "LetsUpgrade",
    date: "Apr 2025",
    image: "/certificates/LUESMMAPR125832_2025-11-21T16_42_49.572Z[1]_page-0001.jpg",
  },
  {
    id: "managing-services",
    title: "Managing Services",
    issuer: "NPTEL",
    date: "Jul-Sep 2025",
    image: "/certificates/WhatsApp Image 2026-03-16 at 5.48.07 PM.jpeg",
  },
  {
    id: "retail-marketing",
    title: "Retail Marketing Strategy",
    issuer: "NPTEL",
    date: "Jul-Sep 2025",
    image: "/certificates/WhatsApp Image 2026-03-16 at 5.48.06 PM.jpeg",
  },
  {
    id: "gen-ai",
    title: "Generative AI Literacy",
    issuer: "Nasscom / FutureSkills Prime",
    date: "Dec 2025",
    image: "/certificates/file-001.png",
  },
  {
    id: "sql",
    title: "SQL Micro Course",
    issuer: "Skill Course",
    date: "Dec 2025",
    image: "/certificates/WhatsApp Image 2026-03-16 at 5.48.08 PM.jpeg",
  },
  {
    id: "power-bi",
    title: "Power BI Micro Course",
    issuer: "Skill Course",
    date: "Dec 2025",
    image: "/certificates/WhatsApp Image 2026-03-16 at 5.48.08 PM (1).jpeg",
  },
  {
    id: "canva-sep",
    title: "Canva Bootcamp",
    issuer: "LetsUpgrade",
    date: "Sept 2024",
    image: "/certificates/WhatsApp Image 2026-03-16 at 5.48.06 PM (1).jpeg",
  },
];
